const Products = [
  {
    id: 1,
    title: 'Beef Burger 1/4lb',
    price: 3.2,
    image: '/images/beef-burger.jpeg',
    href: '',
    category: 'Burger',
  },
  {
    id: 2,
    title: 'Double Beef Burger 1/2lb',
    price: 4.5,
    image: '/images/double-beef-burger.jpeg',
    href: '',
    category: 'Burger',
  },
  {
    id: 3,
    title: 'Cheese Burger 1/4lb',
    price: 3.4,
    image: '/images/cheese-burger.jpeg',
    href: '',
    category: 'Burger',
  },
  {
    id: 4,
    title: 'Chicken Kabab Burger',
    price: 3.2,
    image: '/images/kabab-burger.jpeg',
    href: '',
    category: 'Burger',
  },
  {
    id: 5,
    title: 'Veggie Burger',
    price: 3.5,
    image: '/images/veggie-Burger.jpeg',
    href: '',
    category: 'Burger',
  },
  {
    id: 6,
    title: 'Chicken Fillet Burger',
    price: 3.5,
    image: '/images/chicken-fillet-burger.jpeg',
    href: '',
    category: 'Burger',
  },

  {
    id: 7,
    title: 'Roast Chicken Breast',
    description: '1 Piece',
    price: 1.7,
    image: '/images/roasted-chicken-breast.jpeg',
    href: '',
    category: 'S F Chicken',
  },
  {
    id: 8,
    title: 'Honey-Garlic-Chicken',
    description: '2 Piece',
    price: 3.4,
    image: '/images/Honey-Garlic-Chicken.jpg',
    href: '',
    category: 'S F Chicken',
  },
  {
    id: 9,
    title: 'Tropical-Roasted-Chicken',
    description: '8 Pieces Wings',
    price: 3.7,
    image: '/images/Tropical-Roasted-Chicken.jpg',
    href: '',
    category: 'S F Chicken',
  },
  // {
  //   id: 10,
  //   title: 'My Product',
  //   price: 14,
  //   image: '/images/Pizza.jpg',
  //   href: '',
  //   category: 'S F Chicken',
  // },
  // {
  //   id: 11,
  //   title: 'My Product',
  //   price: 14,
  //   image: '/images/Pizza.jpg',
  //   href: '',
  //   category: 'S F Chicken',
  // },
  // {
  //   id: 12,
  //   title: 'My Product',
  //   price: 14,
  //   image: '/images/Pizza.jpg',
  //   href: '',
  //   category: 'S F Chicken',
  // },
  // {
  //   id: 13,
  //   title: 'Margarita',
  //   description: 'Cheese & tomato',
  //   price: 14,
  //   image: '/images/margarita-cheese-tomato.jpeg',
  //   href: '',
  //   category: 'Pizza',
  // },

  // {
  //   id: 14,
  //   title: 'pizza-margarita',
  //   description: 'Base & cheese',
  //   price: 14,
  //   image: '/images/margarita pizza.jpg',
  //   href: '',
  //   category: 'Pizza',
  // },
  // {
  //   id: 15,
  //   title: 'Hawaiian - 12" Large 8 Pieces',
  //   description: 'Ham & pineapple or Ham & mushroom',
  //   price: 15.99,
  //   image: '/images/hawaiian-pizza.jpeg',
  //   href: '',
  //   category: 'Pizza',
  // },
  // {
  //   id: 16,
  //   title: 'Hawaiian',
  //   description: 'Ham & pineapple or Ham & mushroom',
  //   price: 10,
  //   image: '/images/hawaiian-pizza2.jpg',
  //   href: '',
  //   category: 'Pizza',
  // },
  // {
  //   id: 17,
  //   title: 'Veggie',
  //   description: 'Mushrooms,onion,green peppers & sweetcorn',
  //   price: 12.99,
  //   image: '/images/veggie-pizza.jpeg',
  //   href: '',
  //   category: 'Pizza',
  // },
  // {
  //   id: 18,
  //   title: 'Veggie Hot',
  //   description:
  //     'Mushrooms,onion,green peppers,sweetcorn & green chilli & jalapenos',
  //   price: 12.99,
  //   image: '/images/veggie-jalapeno-pizza.jpeg',
  //   href: '',
  //   category: 'Pizza',
  // },

  // {
  //   id: 19,
  //   title: 'Mini Fish & Chips',
  //   price: 4.7,
  //   image: '/images/fish_chips.jpg',
  //   href: '',
  //   category: 'Specials',
  // },
  // {
  //   id: 20,
  //   title: 'Sausage & Chips',
  //   price: 3.5,
  //   image: '/images/sausage-chips.jpg',
  //   href: '',
  //   category: 'Specials',
  // },
  // {
  //   id: 21,
  //   title: 'Roe & Chips',
  //   price: 3.5,
  //   image: '/images/roe-chips.jpeg',
  //   href: '',
  //   category: 'Specials',
  // },
  // {
  //   id: 22,
  //   title: 'My Product',
  //   price: 14,
  //   image: '/images/Pizza.jpg',
  //   href: '',
  //   category: 'Specials',
  // },
  // {
  //   id: 23,
  //   title: 'My Product',
  //   price: 14,
  //   image: '/images/Pizza.jpg',
  //   href: '',
  //   category: 'Specials',
  // },
  // {
  //   id: 24,
  //   title: 'My Product',
  //   price: 14,
  //   image: '/images/Pizza.jpg',
  //   href: '',
  //   category: 'Specials',
  // },
];

export default Products;
